#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := apds9960

EXTRA_COMPONENT_DIRS := $(shell pwd)/../components/ArduinoJson

include $(IDF_PATH)/make/project.mk
IDF_PATH := $(IOT_SOLUTION_PATH)/submodule/esp-idf/
include $(IOT_SOLUTION_PATH)/components/component_conf.mk
